name: CI for Simple HTML App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or any recent stable version, e.g., '18'

      - name: Install HTMLHint
        run: npm install -g htmlhint # Install HTMLHint globally

      - name: Validate HTML with HTMLHint
        run: htmlhint index.html # Run HTMLHint on your index.html file

      - name: Confirm index.html exists
        run: |
          ls -l
          if [ ! -f "index.html" ]; then
            echo "Error: index.html not found!"
            exit 1
          fi
          echo "index.html found. Basic file presence check passed!"

      - name: CI workflow finished
        run: echo "CI workflow completed successfully for ${{ github.ref_name }} branch!"
