name: CI for Simple HTML App

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main # This workflow also runs when a Pull Request targets 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The operating system where your CI steps will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This action gets your repository code onto the CI server

      - name: Validate HTML with HTMLHint
        uses: athul/html-lint-action@v2 # This is our "test" step!
        with:
          filepath: index.html # Tell the linter which file to check

      - name: Confirm index.html exists
        run: |
          ls -l # List files to show what's there
          if [ ! -f "index.html" ]; then # Check if index.html is missing
            echo "Error: index.html not found!"
            exit 1 # Fail the CI if it's missing
          fi
          echo "index.html found. Basic file presence check passed!"

      - name: CI workflow finished
        run: echo "CI workflow completed successfully for ${{ github.ref_name }} branch!"
